### ISSUE TITLE
EF300 capacity node CPU very High

### ISSUE THREAD

**Issue by yangt777** [NetApp/beegfs#13]
When I use EF300 + 210* 8T SATA disk, 1 BU include 420* 8T SATA disk, use ansible script will create 168 LUN, that very huge number, When using this configuration, the redhat cluster also failed due to too many resources. I then adjusted the raid size of EF300 to 20, so that the number of LUNs was reduced to 84. The redhat cluster was in normal state at this time, but I found that the node CPU usage was always 100%. 
I check the node have 20 beegfs-storage service running，and EF600 nvme node only have 4 beegfs-storage service.
I think that why SATA node CPU utilization 100%.
In this scenario, I would like to increase the LUN size to reduce the number of LUNs, or use DDP? This may be a better choice for EF300, but I don't know how to adjust it in the script.

![Image](https://github.com/user-attachments/assets/cfb5beac-8dfe-41fe-9151-f8b4cc5b4da7)
![Image](https://github.com/user-attachments/assets/cddf1a9a-101e-4afa-b416-45e2638844b5)

beegfs_targets:
  b10a01:
    eseries_storage_pool_configuration:
      - name: beegfs_s101_s102
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: "{{ stor_pct }}"
            owning_controller: A
          - size: "{{ stor_pct }}"
            owning_controller: A

Can I change raid_level raid6 change to DDP ？ So I can increase the disk to 200

**Comment by VuTran007** [comment]
@yangt777 

As a standard practice, we assign only one BeeGFS storage service per InfiniBand interface for host-to-array connections. For example, the EF600 NVMe node is equipped with four InfiniBand interfaces, corresponding to four host-to-array connections.

When configuring storage, you have the option to use either RAID6 or DDP (Dynamic Disk Pool) targets. RAID6 generally offers better performance, while DDP provides greater usable capacity. We recommend using either a 10-drive RAID6 or a 30-drive DDP configuration, depending on your specific requirements.


For example, to map several RAID6 LUNs from an array to a BeeGFS storage service, you can configure your inventory files as shown below:

// stor_01.yml

```
beegfs_targets:
  b10a01:
    eseries_storage_pool_configuration:
      - name: beegfs_s1_s2_vg1  # Volume group 1 for stor_01 and stor_02
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: "{{ stor_pct }}"  # Create one LUN in beegfs_s1_s2_vg1 for stor_01
            owning_controller: A

      - name: beegfs_s1_s2_vg2  # Volume group 2 for stor_01 and stor_02
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: "{{ stor_pct }}"
            owning_controller: A

      - name: beegfs_s1_s2_vg3  # Volume group 3 for stor_01 and stor_02
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: "{{ stor_pct }}"
            owning_controller: A
```

// stor_02.yml

```
beegfs_targets:
  b10a01:
    eseries_storage_pool_configuration:
      - name: beegfs_s1_s2_vg1
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: "{{ stor_pct }}"  # Create one LUN in beegfs_s1_s2_vg1 for stor_02
            owning_controller: B

      - name: beegfs_s1_s2_vg2
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: "{{ stor_pct }}"
            owning_controller: B

      - name: beegfs_s1_s2_vg3
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: "{{ stor_pct }}"
            owning_controller: B
```

If you prefer to use DDP volumes, configure your inventory as follows:

// stor_01.yml

```
beegfs_targets:
  b10a01:
    eseries_storage_pool_configuration:
      - name: beegfs_s1_s2_vg1
        raid_level: raidDiskPool
        criteria_drive_count: 30
        common_volume_configuration:
          segment_size_kb: 128
        volumes:
          - size: "{{ stor_pct }}"
            owning_controller: A

      - name: beegfs_s1_s2_vg2
        raid_level: raidDiskPool
        criteria_drive_count: 30
        common_volume_configuration:
          segment_size_kb: 128
        volumes:
          - size: "{{ stor_pct }}"
            owning_controller: A

      - name: beegfs_s1_s2_vg3
        raid_level: raidDiskPool
        criteria_drive_count: 30
        common_volume_configuration:
          segment_size_kb: 128
        volumes:
          - size: "{{ stor_pct }}"
            owning_controller: A
```

For stor_02.yml, simply change `owning_controller: A` to `owning_controller: B` for each volume group.
